### ISSUE TITLE
Methods - method in table 1.

### ISSUE THREAD

**Issue by sr320** [jldimond/Coral-CpG-ratio-MS#10]
approach used is not necessary

**Comment by jldimond** [comment]
Not totally sure what you mean here - do you mean the column on the sequencing technology used?

**Comment by sr320** [comment]
Correct

**Comment by jldimond** [comment]
I think in an earlier comment you suggested that I include the technology used in the table. So I'm a little confused, but I'm happy to take it out if you want me to...
