### ISSUE TITLE
Discussion outline

### ISSUE THREAD

**Issue by sr320** [jldimond/Coral-CpG-ratio-MS#27]
Please provide an outline for discussion here

**Comment by jldimond** [comment]
You mean just some bullets with main ideas for each paragraph?

**Comment by sr320** [comment]
yes

**Comment by jldimond** [comment]
Outline:
1. Summary of how the study fits into bigger picture and main findings.
2. CpG O/E distributions in corals and how they may relate to overall methylation levels, especially relative to other taxa. Discussion of how methylation reflects broad evolutionary relationships, but the relationship can break down at finer taxonomic levels.
3. Partitioning of genes into high and low CpG O/E fractions based on housekeeping vs. inducible functions. Discussion of how housekeeping genes are common among different tissues and species, which seems odd given that they are predicted to be subject to higher mutation rates.
4. Further discussion of hypermethylated genes and relationship between methylation and expression.
5. Association between hypomethylated genes and inducible expression, and potential explanations (MERV theory).
6. Further discussion of hypomethylated genes, with emphasis on how DEGs are overrepresented by inducible genes and underrepresented by housekeeping genes. Discussion of caveats to DEG/hypomethylation pattern and how most information we have is only correlative.
7. Potential transgenerational influence of DNA methylation and need for more studies.
8. Concluding paragraph.

**Comment by sr320** [comment]
Here is something more concrete. - 
- Wow this is first time....- great stuff! (optional)
- **Finding 1 - Bimodal**
- similar / disimilar in other taxa
- minor differences in species?
- **Finding 2 - methylation based on gene function**
- What are all possible explanations?
- Similar / dissimilar other taxa
- Ecological ramifications
- any differences across corals
- **Finding 2.5 - relationship of methylation and expression (DEG)**
  (There should be some logical transition from above section.
