### ISSUE TITLE
Ahya blast diff

### ISSUE THREAD

**Issue by sr320** [jldimond/Coral-CpG-ratio-MS#28]
Running Ahya blast, I got a little different number 

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/sr320’s_iMac_1B3AFBCC.png" alt="sr320’s_iMac_1B3AFBCC.png"/>

no big deal but likely due to version of swissprot database, should name version you used.

**Comment by jldimond** [comment]
The version (date downloaded) is in the Methods section...
