### ISSUE TITLE
Multiple Contig IDs in CpG table

### ISSUE THREAD

**Issue by sr320** [jldimond/Coral-CpG-ratio-MS#29]
What is the explanation of multiple ID in this table?

And why the Nan lines?

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/sr320’s_iMac_1B3AFCCC.png" alt="sr320’s_iMac_1B3AFCCC.png"/>

**Comment by jldimond** [comment]
The multiple IDs are because some contigs fall into more than one GOslim bin (Mac's analysis was the same).

As for the NaN lines, I never got them when I was running in Linux, but I get them running the same code on Mac OS. They are easily filtered out in R so I don't worry about them.

**Comment by sr320** [comment]
maybe I misunderstand - Line 6, is that 1 contig with a 3 number name? or three contigs?

**Comment by jldimond** [comment]
It's their contig name - a 3-number name. Something to do with isogroups maybe?
