### ISSUE TITLE
Fasta files

### ISSUE THREAD

**Issue by sr320** [jldimond/Coral-CpG-ratio-MS#3]
Place fasta files (n=6) in directory

**Comment by jldimond** [comment]
Will do

**Comment by jldimond** [comment]
Wondering if you can help me decide which data to download here from the category "Mfav_pool". UniSeqs? or Contigs?

![screenshot from 2015-02-19 11 10 48](https://cloud.githubusercontent.com/assets/9869457/6273977/a0f487e4-b828-11e4-9115-54300d3cbe2f.png)

**Comment by sr320** [comment]
Uniseqs 
but go ahead and download both and label probably
