### ISSUE TITLE
Timeline for Completion

### ISSUE THREAD

**Issue by sr320** [jldimond/Coral-CpG-ratio-MS#4]
Lets go ahead and lay out a timeline for completion.

**Comment by jldimond** [comment]
How about:
-analysis complete by April 15th 
-full draft complete by May 15th
-submission by June 15th (ahead of July 1st deadline)

**Comment by sr320** [comment]
Lets have more fine grained deadlines....

Methods - March 30
Results - April 15th (w Analysis)
Discussion - April 30 
Introduction - May 7
Abstract, Citations, Formatting - May 15

And maybe an outline asap? separate md file

**Comment by jldimond** [comment]
Sounds good...I have never done an outline for a publication in the past but I'll give it a shot.

**Comment by jldimond** [comment]
https://github.com/jldimond/Coral-CpG-ratio-MS/blob/master/outline.md

**Comment by sr320** [comment]
Running a bit behind schedule? Any major hurdles?

**Comment by jldimond** [comment]
Nothing major...the main issue is lack of time. I've been working on stats and plotting in R lately and I'm still getting used to it. I may have trouble meeting those deadlines we set but I'm not too worried about the July 1st deadline for submission.
