### ISSUE TITLE
Methods should refer to IPython nb 

### ISSUE THREAD

**Issue by sr320** [jldimond/Coral-CpG-ratio-MS#6]
Methods should refer to ipython notebooks so someone could reproduce 
1) annoation
2) germline methylation prediction

**Comment by jldimond** [comment]
Yes, I just haven't gotten there yet.

It looks like you wrote some methods in results.md. Would you like me to incorporate some of that content into what I have in methods.md?

**Comment by sr320** [comment]
that was just some older artifact - I fixed

**Comment by sr320** [comment]
Assuming notebooks in 
ipynb directory are said notebooks

I have started to edit
`Amil_blast_anno.ipynb`

**Comment by jldimond** [comment]
Yes, I am also making changes to notebooks in that directory, but to the CpG notebooks.
